<?php

use App\Channels\GitHub\AppService as GitHubAppService;
use App\Services\PullRequestBodyUpdater;

beforeEach(function () {
    config()->set('yak.channels.github.installation_id', 77);
});

test('swaps the raw webm fallback link for the rendered reviewer cut', function () {
    $existing = "## Yak Automated PR\n\nSome summary\n\n### Video walkthrough\n\n- [walkthrough.webm](https://signed.example/webm?exp=1)\n\n### Files changed\n\n- `foo.php`";

    $github = $this->mock(GitHubAppService::class);
    $github->shouldReceive('getPullRequest')
        ->once()
        ->with(77, 'owner/repo', 42)
        ->andReturn(['body' => $existing]);

    $github->shouldReceive('updatePullRequest')
        ->once()
        ->withArgs(function (int $installationId, string $repo, int $num, array $data): bool {
            return $installationId === 77
                && $repo === 'owner/repo'
                && $num === 42
                && str_contains($data['body'], '[reviewer-cut.mp4](https://signed.example/mp4)')
                && ! str_contains($data['body'], 'walkthrough.webm')
                && str_contains($data['body'], '### Files changed');
        })
        ->andReturn(['body' => 'ok']);

    $updater = new PullRequestBodyUpdater($github);
    $updater->setReviewerCut(
        repoFullName: 'owner/repo',
        prNumber: 42,
        reviewerCutUrl: 'https://signed.example/mp4',
    );
});

test('creates the Video walkthrough section if missing', function () {
    $existing = "## Summary\n\nNo walkthrough yet\n\n### Files changed\n\n- `foo.php`";

    $github = $this->mock(GitHubAppService::class);
    $github->shouldReceive('getPullRequest')
        ->once()
        ->with(77, 'owner/repo', 42)
        ->andReturn(['body' => $existing]);

    $github->shouldReceive('updatePullRequest')
        ->once()
        ->withArgs(function (int $installationId, string $repo, int $num, array $data): bool {
            return str_contains($data['body'], '### Video walkthrough')
                && str_contains($data['body'], '[reviewer-cut.mp4](https://signed.example/mp4)');
        })
        ->andReturn(['body' => 'ok']);

    $updater = new PullRequestBodyUpdater($github);
    $updater->setReviewerCut('owner/repo', 42, 'https://signed.example/mp4');
});

test('handles empty body by creating the Video walkthrough section', function () {
    $github = $this->mock(GitHubAppService::class);
    $github->shouldReceive('getPullRequest')
        ->once()
        ->andReturn(['body' => null]);

    $github->shouldReceive('updatePullRequest')
        ->once()
        ->withArgs(function ($installationId, $repo, $num, array $data): bool {
            return str_contains($data['body'], '### Video walkthrough')
                && str_contains($data['body'], '[reviewer-cut.mp4]');
        })
        ->andReturn(['body' => 'ok']);

    $updater = new PullRequestBodyUpdater($github);
    $updater->setReviewerCut('owner/repo', 42, 'https://signed.example/mp4');
});

test('is idempotent when the plain-link form is already present and no thumbnail is supplied', function () {
    $existing = "### Video walkthrough\n\n- [reviewer-cut.mp4](https://signed.example/old?exp=1)\n";

    $github = $this->mock(GitHubAppService::class);
    $github->shouldReceive('getPullRequest')
        ->once()
        ->andReturn(['body' => $existing]);

    $github->shouldNotReceive('updatePullRequest');

    $updater = new PullRequestBodyUpdater($github);
    // Plain-text link already present, we're not offering a thumbnail — no-op.
    $updater->setReviewerCut('owner/repo', 42, 'https://signed.example/new?exp=2');
});

test('preserves content after the Video walkthrough section (no heading before the warning callout)', function () {
    // Regression: when Files changed was empty so the Video walkthrough
    // was the last heading, the previous regex greedy-matched all the
    // way through the `---` divider and warning callout, leaving the
    // thumbnail jammed against the warning.
    $existing = "## Yak Automated PR\n\n### Video walkthrough\n\n- [walkthrough.webm](https://signed.example/webm)\n\n---\n> **Warning:** This PR was generated by Yak. Review before merging.";

    $github = $this->mock(GitHubAppService::class);
    $github->shouldReceive('getPullRequest')
        ->once()
        ->andReturn(['body' => $existing]);

    $github->shouldReceive('updatePullRequest')
        ->once()
        ->withArgs(function ($i, $r, $n, array $data): bool {
            return str_contains($data['body'], '![Watch reviewer-cut.mp4](https://signed.example/thumb)')
                && str_contains($data['body'], '> **Warning:**')
                && str_contains($data['body'], "\n\n---\n> ") // blank line + divider + callout preserved
                && ! str_contains($data['body'], 'walkthrough.webm');
        })
        ->andReturn(['body' => 'ok']);

    $updater = new PullRequestBodyUpdater($github);
    $updater->setReviewerCut(
        repoFullName: 'owner/repo',
        prNumber: 42,
        reviewerCutUrl: 'https://signed.example/video',
        thumbnailUrl: 'https://signed.example/thumb',
    );
});

test('upgrades plain-text link to image embed when a thumbnail becomes available', function () {
    $existing = "### Video walkthrough\n\n- [reviewer-cut.mp4](https://signed.example/video?exp=1)\n\n### Files changed\n\n- `foo.php`";

    $github = $this->mock(GitHubAppService::class);
    $github->shouldReceive('getPullRequest')
        ->once()
        ->andReturn(['body' => $existing]);

    $github->shouldReceive('updatePullRequest')
        ->once()
        ->withArgs(function ($i, $r, $n, array $data): bool {
            return str_contains($data['body'], '![Watch reviewer-cut.mp4](https://signed.example/thumb)')
                && str_contains($data['body'], '](https://signed.example/video)')
                && ! str_contains($data['body'], '- [reviewer-cut.mp4]')
                && str_contains($data['body'], '### Files changed');
        })
        ->andReturn(['body' => 'ok']);

    $updater = new PullRequestBodyUpdater($github);
    $updater->setReviewerCut(
        repoFullName: 'owner/repo',
        prNumber: 42,
        reviewerCutUrl: 'https://signed.example/video',
        thumbnailUrl: 'https://signed.example/thumb',
    );
});

test('is idempotent when the image-embed form is already present', function () {
    $existing = "### Video walkthrough\n\n[![Watch reviewer-cut.mp4](https://signed.example/thumb?exp=1)](https://signed.example/video?exp=1)\n";

    $github = $this->mock(GitHubAppService::class);
    $github->shouldReceive('getPullRequest')
        ->once()
        ->andReturn(['body' => $existing]);

    $github->shouldNotReceive('updatePullRequest');

    $updater = new PullRequestBodyUpdater($github);
    $updater->setReviewerCut(
        repoFullName: 'owner/repo',
        prNumber: 42,
        reviewerCutUrl: 'https://signed.example/video?exp=2',
        thumbnailUrl: 'https://signed.example/thumb?exp=2',
    );
});
